lab7: main.o
	g++ -std=c++11 -g -Wall main.o -o lab7

main.o:  insertionSort.cpp mergeSort.cpp bubbleSort.cpp quickSort.cpp selectionSort.cpp main.cpp
	g++ -std=c++11 -g -Wall -c main.cpp

clean:
	rm *.o lab7
	clean done
